### ISSUE TITLE
(logs) trying to read voiceChannel property of an undefined mem

### ISSUE THREAD

**Issue by pianiststickman** [pinano-discord/Pinano-Discord-Bot#18]
Found a few instances of the following in the logs after deploying the 3rd-party stats update:

```
(node:28564) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'voiceChannel' of undefined
    at client.loadUserData (/home/pinanostaff/pinano/commands/general/stats.js:78:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

Line 78 is the following:

```if (mem.voiceChannel != null && guild.permitted_channels.includes(mem.voiceChannel.id) && !mem.mute && mem.s_time != null)```

... indicating that mem is null, but I can't quite figure out how this might have happened, considering 1) if the subject of the query was specified by the user, we should have returned an error to the user if the user was not found, and 2) if the user didn't specify the subject of the query, the user IS the subject of the query.

**Comment by pianiststickman** [comment]
No repro
