### ISSUE TITLE
p!info broken

### ISSUE THREAD

**Issue by pianiststickman** [pinano-discord/Pinano-Discord-Bot#57]
```
RangeError: RichEmbed field values may not exceed 1024 characters.
    at RichEmbed.addField (/home/pinano/pinano/node_modules/discord.js/src/structures/RichEmbed.js:164:36)
    at Object.run (/home/pinano/pinano/commands/general/info.js:24:15)
    at Client.client.on (/home/pinano/pinano/library/client_events.js:40:94)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
{ DiscordAPIError: Unknown Message
    at item.request.gen.end (/home/pinano/pinano/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:79:15)
    at then (/home/pinano/pinano/node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'DiscordAPIError',
  message: 'Unknown Message',
  path: '/api/v7/channels/205004956774825984/messages/584518131394019388',
  code: 10008,
  method: 'DELETE' }```

**Comment by pianiststickman** [comment]
p!info now deprecated.
